<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EquipmentRental.Data\EquipmentRental.Data.csproj" />
    <ProjectReference Include="..\EquipmentRental.Data.Models\EquipmentRental.Data.Models.csproj" />
  </ItemGroup>

</Project>
